<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.1">
  <PropertyGroup>
    <Authors></Authors>
    <Company></Company>
    <Version>1.0.0.7</Version>
    <Description>A sample plugin.</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/goatcorp/SamplePlugin</PackageProjectUrl>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="DalamudPackager" Version="15.0.0" />
  </ItemGroup>
</Project>
